### ISSUE TITLE
Some char is unexpected

### ISSUE THREAD

**Issue by relax-code-relax-life** [sindresorhus/is-fullwidth-code-point#12]
For example:

``` javascript
 console.log(isFullwidthCodePoint(parseInt('1B11E',16)))  // false
```

Due to  in the [EastAsianWidth.txt](https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt) I found this:

```
1B100..1B11E;W   # Lo    [31] HENTAIGANA LETTER RE-3..HENTAIGANA LETTER N-MU-MO-2
```

So I think the value about `1B11E` should be true ?

**Comment by sindresorhus** [comment]
What exactly is unexpected? What did you expect and why?

**Comment by relax-code-relax-life** [comment]
I'm sorry  my description is too short and is ambiguous.
I have edited.

**Comment by sindresorhus** [comment]
This was fixed in https://github.com/sindresorhus/is-fullwidth-code-point/releases/tag/v5.0.0
