### ISSUE TITLE
License / attribution

### ISSUE THREAD

**Issue by Offirmo** [sindresorhus/is-fullwidth-code-point#3]
Hello Sindre,

your code looks a lot like https://github.com/timoxley/wcwidth/blob/master/docs/index.md

by any chance did you take the algorithm somewhere? That could require an attribution.

**Comment by sindresorhus** [comment]
The code is made from code points documented in http://www.unix.org/Public/UNIDATA/EastAsianWidth.txt The link is dead now though.

See: https://github.com/sindresorhus/is-fullwidth-code-point/blob/master/index.js#L8-L9

**Comment by Offirmo** [comment]
ok. Thanks for answering!
